/**
 * Folder: src/utils/
 * Description: Stores helper utilities, presets, and initial states.
 * This file: fakeChatPresets.ts (Preset chat templates including user's screenshot replica).
 */

import type { FakeChatState } from '../types/fakeChat'

export const DEFAULT_AVATARS = [
  {
    id: 'anime-girl',
    label: 'Anime Girl (Seperti Screenshot)',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'boy-cool',
    label: 'Cool Guy',
    url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'girl-aesthetic',
    label: 'Aesthetic Girl',
    url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'store-logo',
    label: 'Online Store',
    url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-cute',
    label: 'Kucing Lucu',
    url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=150&auto=format&fit=crop&q=80',
  },
]

export const PRESET_CHATS: { id: string; name: string; description: string; state: FakeChatState }[] = [
  {
    id: 'user-screenshot',
    name: 'Replika Screenshot (Rpl Keisya)',
    description: 'Percakapan YT Premium & Genshin Quest di perpus (Sesuai gambar referensi)',
    state: {
      platform: 'desktop',
      theme: 'dark',
      contact: {
        name: 'Rpl Keisya[1]',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        status: 'online',
        isOnline: true,
        isTyping: false,
        isVerified: false,
        isGroup: false,
      },
      header: {
        showCallButtons: true,
        showSearchButton: true,
        showMenuButton: true,
        pinnedMessage: {
          enabled: true,
          title: '',
          text: '45.58.47.49 3TEtyff7CcvM2nzY',
        },
      },
      mobileStatus: {
        showStatusBar: true,
        time: '20:56',
        batteryPercentage: 78,
        isCharging: false,
        signalStrength: 4,
        networkType: '5G',
        showWifi: true,
        showNotch: true,
        showHomeIndicator: true,
      },
      wallpaper: {
        type: 'doodle',
        solidColor: '#0b141a',
        doodleOpacity: 12,
      },
      inputPlaceholder: 'Ketik pesan',
      showMockupFrame: false,
      zoomLevel: 100,
      messages: [
        {
          id: 'date-1',
          type: 'date_divider',
          sender: 'them',
          text: 'Kemarin',
          time: '',
        },
        {
          id: 'm1',
          type: 'text',
          sender: 'me',
          text: 'How to claim yt premium?',
          time: '19.33',
          status: 'double_blue',
        },
        {
          id: 'm2',
          type: 'text',
          sender: 'me',
          text: '3 month?',
          time: '19.33',
          status: 'double_blue',
        },
        {
          id: 'm3',
          type: 'text',
          sender: 'me',
          text: 'Or what',
          time: '19.33',
          status: 'double_blue',
        },
        {
          id: 'm4',
          type: 'text',
          sender: 'them',
          text: 'fake',
          time: '19.34',
        },
        {
          id: 'm5',
          type: 'text',
          sender: 'them',
          text: 'Do you already get?',
          time: '19.34',
        },
        {
          id: 'm6',
          type: 'text',
          sender: 'me',
          text: "I'm literally asking how to claim 🌵",
          time: '19.34',
          status: 'double_blue',
        },
        {
          id: 'm7',
          type: 'text',
          sender: 'them',
          text: 'go to fitur premium then theres yt premium',
          time: '19.35',
        },
        {
          id: 'm8',
          type: 'text',
          sender: 'them',
          text: 'but i not get',
          time: '19.35',
        },
        {
          id: 'm9',
          type: 'text',
          sender: 'them',
          text: 'idk why',
          time: '19.35',
        },
        {
          id: 'm10',
          type: 'text',
          sender: 'them',
          text: 'scam',
          time: '19.35',
        },
        {
          id: 'm11',
          type: 'text',
          sender: 'me',
          text: 'Is each day different poster?',
          time: '20.49',
          status: 'double_blue',
        },
        {
          id: 'm12',
          type: 'text',
          sender: 'me',
          text: "If it is let's go to perpus",
          time: '20.49',
          status: 'double_blue',
        },
        {
          id: 'm13',
          type: 'text',
          sender: 'them',
          text: 'we need 3 poster i think',
          time: '20.55',
          reactions: [{ emoji: '🙂', count: 1 }],
        },
        {
          id: 'm14',
          type: 'text',
          sender: 'me',
          text: 'Sure',
          time: '20.55',
          status: 'double_blue',
        },
        {
          id: 'm15',
          type: 'text',
          sender: 'them',
          text: 'yeah sure',
          time: '20.55',
          replyTo: {
            id: 'm12',
            senderName: 'Anda',
            text: "If it is let's go to perpus",
          },
        },
        {
          id: 'm16',
          type: 'text',
          sender: 'me',
          text: 'Are you fine go to perpus? Or you dont want?',
          time: '20.55',
          status: 'double_blue',
        },
        {
          id: 'm17',
          type: 'text',
          sender: 'me',
          text: 'I want productive Zzz',
          time: '20.56',
          status: 'double_blue',
        },
        {
          id: 'm18',
          type: 'text',
          sender: 'them',
          text: 'bro go to perpus to download something',
          time: '20.56',
        },
        {
          id: 'm19',
          type: 'text',
          sender: 'me',
          text: 'Nah i want do genshin quest',
          time: '20.56',
          status: 'double_blue',
        },
      ],
    },
  },
  {
    id: 'olshop-cs',
    name: 'Customer Service & Olshop',
    description: 'Konfirmasi pesanan, resi pengiriman, dan tanya stok barang',
    state: {
      platform: 'android',
      theme: 'light',
      contact: {
        name: 'GiggleBox Official Store 🛍️',
        avatarUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=150&auto=format&fit=crop&q=80',
        status: 'online',
        isOnline: true,
        isTyping: false,
        isVerified: true,
        isGroup: false,
      },
      header: {
        showCallButtons: true,
        showSearchButton: true,
        showMenuButton: true,
        pinnedMessage: {
          enabled: true,
          title: 'Promo Flash Sale 9.9',
          text: 'Gunakan voucher DISKON50K untuk min pembelian 100rb!',
        },
      },
      mobileStatus: {
        showStatusBar: true,
        time: '14:20',
        batteryPercentage: 92,
        isCharging: true,
        signalStrength: 4,
        networkType: '5G',
        showWifi: true,
        showNotch: true,
        showHomeIndicator: true,
      },
      wallpaper: {
        type: 'doodle',
        solidColor: '#efeae2',
        doodleOpacity: 10,
      },
      inputPlaceholder: 'Ketik pesan',
      showMockupFrame: true,
      zoomLevel: 100,
      messages: [
        {
          id: 's1',
          type: 'system',
          sender: 'them',
          text: '🔒 Pesan dan panggilan terenkripsi secara end-to-end. Tidak seorang pun di luar chat ini, termasuk WhatsApp, yang dapat membaca atau mendengarkannya.',
          time: '',
        },
        {
          id: 'd1',
          type: 'date_divider',
          sender: 'them',
          text: 'Hari ini',
          time: '',
        },
        {
          id: 'm1',
          type: 'text',
          sender: 'me',
          text: 'Halo kak, apa hoodie warna midnight blue size L masih ready?',
          time: '14.15',
          status: 'double_blue',
        },
        {
          id: 'm2',
          type: 'text',
          sender: 'them',
          text: 'Halo kak! 👋 Masih ready stock ya, siap kirim hari ini sebelum jam 17:00 WIB.',
          time: '14.16',
        },
        {
          id: 'm3',
          type: 'image',
          sender: 'them',
          text: '',
          imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80',
          imageCaption: 'Foto real pict katalog Hoodie Midnight Blue',
          time: '14.17',
          reactions: [{ emoji: '🔥', count: 1 }],
        },
        {
          id: 'm4',
          type: 'text',
          sender: 'me',
          text: 'Wah keren! Saya langsung checkout via web yaa kak.',
          time: '14.18',
          status: 'double_blue',
        },
        {
          id: 'm5',
          type: 'text',
          sender: 'them',
          text: 'Siap kak, ditunggu ya. Terima kasih banyak sudah berbelanja di GiggleBox! ✨',
          time: '14.19',
          reactions: [{ emoji: '❤️', count: 1 }],
        },
      ],
    },
  },
  {
    id: 'media-audio-showcase',
    name: 'Voice Note & Media Rich Chat',
    description: 'Contoh kiriman Voice Note, File Dokumen PDF, Foto, dan Reaksi Emoji',
    state: {
      platform: 'ios',
      theme: 'dark',
      contact: {
        name: 'Dafa Developer 🚀',
        avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
        status: 'terakhir dilihat hari ini pukul 11.20',
        isOnline: false,
        isTyping: false,
        isVerified: false,
        isGroup: false,
      },
      header: {
        showCallButtons: true,
        showSearchButton: true,
        showMenuButton: true,
      },
      mobileStatus: {
        showStatusBar: true,
        time: '11:25',
        batteryPercentage: 45,
        isCharging: false,
        signalStrength: 3,
        networkType: 'LTE',
        showWifi: true,
        showNotch: true,
        showHomeIndicator: true,
      },
      wallpaper: {
        type: 'doodle',
        solidColor: '#0b141a',
        doodleOpacity: 12,
      },
      inputPlaceholder: 'Pesan',
      showMockupFrame: true,
      zoomLevel: 100,
      messages: [
        {
          id: 'd1',
          type: 'date_divider',
          sender: 'them',
          text: 'Hari ini',
          time: '',
        },
        {
          id: 'm1',
          type: 'audio',
          sender: 'them',
          text: '',
          audioDuration: '0:38',
          audioProgress: 60,
          audioSpeed: '1.5x',
          time: '11.02',
          reactions: [{ emoji: '👍', count: 1 }],
        },
        {
          id: 'm2',
          type: 'document',
          sender: 'me',
          text: '',
          docName: 'Final_Design_System_v2.pdf',
          docPages: '18 halaman',
          docSize: '4.8 MB',
          docExt: 'PDF',
          time: '11.05',
          status: 'double_blue',
        },
        {
          id: 'm3',
          type: 'text',
          sender: 'me',
          text: 'Udah gw kirim PDF spek UI terbarunya ya, cek bagian *halaman 7-12* buat responsive mobile.',
          time: '11.06',
          status: 'double_blue',
        },
        {
          id: 'm4',
          type: 'audio',
          sender: 'me',
          text: '',
          audioDuration: '1:12',
          audioProgress: 100,
          audioSpeed: '1x',
          time: '11.08',
          status: 'double_blue',
        },
        {
          id: 'm5',
          type: 'text',
          sender: 'them',
          text: 'Mantap bro! Gas kita deploy sore ini 🚀',
          time: '11.10',
          reactions: [{ emoji: '🔥', count: 2 }, { emoji: '🎉', count: 1 }],
        },
      ],
    },
  },
]
